.TH "AbilitiesEditor.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbilitiesEditor.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbilitiesEditor\fP"
.br
.RI "API for Abilities objects\&. Modifies tentativeAbilities variable from \fBCreatureEditor\fP "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBabilityType\fP { \fBabilityType\&.comsumption\fP, \fBabilityType\&.defense\fP, \fBabilityType\&.attack\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBabilityType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIcomsumption \fP\fP
.TP
\fB\fIdefense \fP\fP
.TP
\fB\fIattack \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
