.TH "ActionEditor.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionEditor.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBActionEditor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBActionCreatorType\fP { \fBActionCreatorType\&.commActionCreator\fP, \fBActionCreatorType\&.moveActionCreator\fP, \fBActionCreatorType\&.consumeCreator\fP, \fBActionCreatorType\&.reproduceCreator\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBActionCreatorType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIcommActionCreator \fP\fP
.TP
\fB\fImoveActionCreator \fP\fP
.TP
\fB\fIconsumeCreator \fP\fP
.TP
\fB\fIreproduceCreator \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
