.TH "ActivationBehavior" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActivationBehavior \- Interface for objects that implement an activation function\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEmptyActivBehavior\fP, \fBLogisticActivBehavior\fP, \fBLogisticWithNegActivBehav\fP, and \fBTanhActivBehav\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBactivFunct\fP (float input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for objects that implement an activation function\&. 


.SH "Member Function Documentation"
.PP 
.SS "float ActivationBehavior\&.activFunct (float input)"

.PP
Implemented in \fBLogisticActivBehavior\fP, \fBEmptyActivBehavior\fP, \fBLogisticWithNegActivBehav\fP, and \fBTanhActivBehav\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
