.TH "ActionEditorAbstract" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionEditorAbstract
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCommActionEditor\fP, \fBConsumeFromLandEditor\fP, \fBMoveActionEditor\fP, and \fBReproActionEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAction\fP \fBgetAction\fP ()"
.br
.ti -1c
.RI "void \fBsetTimeCost\fP (int cost)"
.br
.ti -1c
.RI "void \fBaddResourceCost\fP (string key, int value)"
.br
.ti -1c
.RI "void \fBsetPriority\fP (int priority)"
.br
.ti -1c
.RI "void \fBsetName\fP (string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAction\fP \fBaction\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ActionEditorAbstract\&.addResourceCost (string key, int value)"

.SS "\fBAction\fP ActionEditorAbstract\&.getAction ()"

.SS "void ActionEditorAbstract\&.setName (string name)"

.SS "void ActionEditorAbstract\&.setPriority (int priority)"

.SS "void ActionEditorAbstract\&.setTimeCost (int cost)"

.SH "Member Data Documentation"
.PP 
.SS "\fBAction\fP ActionEditorAbstract\&.action"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
