.TH "BiasNode" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiasNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetBias\fP (float newBias)"
.br
.RI "sets bias to a value "
.ti -1c
.RI "override void \fBupdateValue\fP ()"
.br
.RI "Updates node value "
.ti -1c
.RI "\fBBiasNode\fP \fBclone\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBBiasNode\fP BiasNode\&.clone ()"

.SS "void BiasNode\&.setBias (float newBias)"

.PP
sets bias to a value 
.SS "override void BiasNode\&.updateValue ()\fC [virtual]\fP"

.PP
Updates node value 
.PP
Implements \fBNode\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
