.TH "BoostRequirement.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoostRequirement.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBoostRequirement\fP"
.br
.RI "Currently not used\&. Boost requirements allow for modifications to abilities, thus giving creatures with certain resources an advantage over other creatures\&. If all creatures are capable of this ability, and have the same boost requirements, they all have the opportunity to gain this advantage\&. However, it should be noted that the relationship between resources and abilities established here does give certain resources more inherent value than others\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
