.TH "CameraPositioner" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CameraPositioner
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBgetterObj\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "GameObject CameraPositioner\&.getterObj"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
