.TH "CommSignal" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommSignal \- The comm network must individually process each comm signal stored in the creatures commList, and save the outputs as action recommendations\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, bool[]> \fBcommProperties\fP"
.br
.RI "Stores message, position, and phenotype\&. "
.in -1c
.SH "Detailed Description"
.PP 
The comm network must individually process each comm signal stored in the creatures commList, and save the outputs as action recommendations\&. 


.SH "Member Data Documentation"
.PP 
.SS "Dictionary<string, bool[]> CommSignal\&.commProperties"

.PP
Stores message, position, and phenotype\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
