.TH "CommAction" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBperform\fP (\fBCreature\fP creature, \fBEcosystem\fP eco)"
.br
.RI "Adds signal to creatures output comm signals\&. (to be iterated over and passed to neighbors)\&. "
.ti -1c
.RI "void \fBassignSignalProps\fP ()"
.br
.RI "Assigns properties of signal "
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void CommAction\&.assignSignalProps ()"

.PP
Assigns properties of signal 
.SS "override void CommAction\&.perform (\fBCreature\fP creature, \fBEcosystem\fP eco)\fC [virtual]\fP"

.PP
Adds signal to creatures output comm signals\&. (to be iterated over and passed to neighbors)\&. 
.PP
Implements \fBAction\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
