.TH "CommSignal.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommSignal.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommSignal\fP"
.br
.RI "The comm network must individually process each comm signal stored in the creatures commList, and save the outputs as action recommendations\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
