.TH "EcosystemGetter" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EcosystemGetter
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetMapWidth\fP ()"
.br
.ti -1c
.RI "int \fBgetMapHeight\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBsimRunnerObj\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int EcosystemGetter\&.getMapHeight ()"

.SS "int EcosystemGetter\&.getMapWidth ()"

.SH "Member Data Documentation"
.PP 
.SS "GameObject EcosystemGetter\&.simRunnerObj"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
