.TH "EmptyActivBehavior" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmptyActivBehavior \- No activation function (node simply uses linear combination)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBActivationBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBactivFunct\fP (float input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
No activation function (node simply uses linear combination)\&. 


.SH "Member Function Documentation"
.PP 
.SS "float EmptyActivBehavior\&.activFunct (float input)"

.PP
Implements \fBActivationBehavior\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
