.TH "GameManager" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GameManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStart\fP ()"
.br
.ti -1c
.RI "void \fBaddEcosystem\fP (\fBEcosystem\fP eco)"
.br
.ti -1c
.RI "void \fBstartUserSimulation\fP (int simSteps)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void GameManager\&.addEcosystem (\fBEcosystem\fP eco)"

.SS "void GameManager\&.Start ()"

.SS "void GameManager\&.startUserSimulation (int simSteps)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
