.TH "HelperValidator.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelperValidator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHelperValidator\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBIntFunct\fP (int x)"
.br
.ti -1c
.RI "delegate void \fBStringFunct\fP (string s)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate void IntFunct (int x)"

.SS "delegate void StringFunct (string s)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
