.TH "HelperValidator" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelperValidator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBvalidateIntegerString\fP (string text)"
.br
.ti -1c
.RI "static bool \fBvalidateFloatString\fP (string text)"
.br
.ti -1c
.RI "static bool \fBsetIntegerFunct\fP (GameObject go, \fBIntFunct\fP setInt, GameObject \fBerrorObj\fP)"
.br
.ti -1c
.RI "static bool \fBsetName\fP (GameObject textBox, GameObject \fBerrorObj\fP, \fBStringFunct\fP stringSetter)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static GameObject \fBerrorObj\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static bool HelperValidator\&.setIntegerFunct (GameObject go, \fBIntFunct\fP setInt, GameObject errorObj)\fC [static]\fP"

.SS "static bool HelperValidator\&.setName (GameObject textBox, GameObject errorObj, \fBStringFunct\fP stringSetter)\fC [static]\fP"

.SS "static bool HelperValidator\&.validateFloatString (string text)\fC [static]\fP"

.SS "static bool HelperValidator\&.validateIntegerString (string text)\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "GameObject HelperValidator\&.errorObj\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
