.TH "InnerInputNode" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InnerInputNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBupdateValue\fP ()"
.br
.RI "This method simply gets the value from inNode\&. "
.ti -1c
.RI "\fBInnerInputNode\fP \fBclone\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNode\fP \fBlinkedNode\fP"
.br
.ti -1c
.RI "string \fBlinkedNetName\fP"
.br
.ti -1c
.RI "\fBCreature\fP \fBparentCreature\fP"
.br
.ti -1c
.RI "int \fBlinkedNodeIndex\fP"
.br
.ti -1c
.RI "int \fBlinkedNodeNetworkLayer\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBInnerInputNode\fP InnerInputNode\&.clone ()"

.SS "override void InnerInputNode\&.updateValue ()\fC [virtual]\fP"

.PP
This method simply gets the value from inNode\&. 
.PP
Implements \fBNode\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string InnerInputNode\&.linkedNetName"

.SS "\fBNode\fP InnerInputNode\&.linkedNode"

.SS "int InnerInputNode\&.linkedNodeIndex"

.SS "int InnerInputNode\&.linkedNodeNetworkLayer"

.SS "\fBCreature\fP InnerInputNode\&.parentCreature"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
