.TH "LogisticWithNegActivBehav.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogisticWithNegActivBehav.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogisticWithNegActivBehav\fP"
.br
.RI "Logistic activation function, but mapped to [-1,1] "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
