.TH "MapEditor.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MapEditor.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMapEditor\fP"
.br
.RI "API for editing the map: a 2D array of \fBLand\fP spaces\&. Used to generate the map, and add resources\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
