.TH "MoveAction" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveAction\fP ()"
.br
.ti -1c
.RI "\fBMoveAction\fP (\fBmoveDir\fP dir)"
.br
.ti -1c
.RI "override void \fBperform\fP (\fBCreature\fP creature, \fBEcosystem\fP eco)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmoveDir\fP \fBdirection\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MoveAction\&.MoveAction ()"

.SS "MoveAction\&.MoveAction (\fBmoveDir\fP dir)"

.SH "Member Function Documentation"
.PP 
.SS "override void MoveAction\&.perform (\fBCreature\fP creature, \fBEcosystem\fP eco)\fC [virtual]\fP"

.PP
Implements \fBAction\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmoveDir\fP MoveAction\&.direction"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
