.TH "NodeEditor.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeEditor.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNodeEditor\fP"
.br
.RI "API for storing different kinds of specific node creators\&. ex\&. - could wrap a SensoryInputNodeCreator\&. Stored by NetworkCreator\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNodeCreatorType\fP { \fBNodeCreatorType\&.siNodeCreator\fP, \fBNodeCreatorType\&.commNodeCreator\fP, \fBNodeCreatorType\&.outputNodeCreator\fP, \fBNodeCreatorType\&.innerInputNodeCreator\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNodeCreatorType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIsiNodeCreator \fP\fP
.TP
\fB\fIcommNodeCreator \fP\fP
.TP
\fB\fIoutputNodeCreator \fP\fP
.TP
\fB\fIinnerInputNodeCreator \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
