.TH "NodeEditorInterface" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeEditorInterface \- Interface that allows all specific node creator objects to be stored by NodeCreator class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBCommNodeEditor\fP, \fBInnerInputNodeEditor\fP, \fBOutputNodeEditor\fP, and \fBSensoryInputNodeEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP \fBgetNode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface that allows all specific node creator objects to be stored by NodeCreator class\&. 


.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP NodeEditorInterface\&.getNode ()"

.PP
Implemented in \fBCommNodeEditor\fP, \fBSensoryInputNodeEditor\fP, \fBInnerInputNodeEditor\fP, and \fBOutputNodeEditor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
