.TH "NonInputNode.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NonInputNode.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNonInputNode\fP"
.br
.RI "Encompasses hidden nodes (which use this class directly) and output nodes (which use the \fBOutputNode\fP class)\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBActivationBehaviorTypes\fP { \fBActivationBehaviorTypes\&.LogisticAB\fP, \fBActivationBehaviorTypes\&.EmptyAB\fP, \fBActivationBehaviorTypes\&.LogWithNeg\fP, \fBActivationBehaviorTypes\&.Tanh\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBActivationBehaviorTypes\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILogisticAB \fP\fP
.TP
\fB\fIEmptyAB \fP\fP
.TP
\fB\fILogWithNeg \fP\fP
.TP
\fB\fITanh \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
