.TH "OutputNodeEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutputNodeEditor \- API for OutputNodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeEditorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutputNodeEditor\fP (\fBOutputNode\fP \fBfoNode\fP, int \fBnodeLayer\fP)"
.br
.ti -1c
.RI "\fBNode\fP \fBgetNode\fP ()"
.br
.ti -1c
.RI "void \fBsetAction\fP (string actionKey)"
.br
.ti -1c
.RI "void \fBsetActivationFunction\fP (\fBActivationBehaviorTypes\fP activType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBOutputNode\fP \fBfoNode\fP"
.br
.ti -1c
.RI "int \fBnodeLayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
API for OutputNodes\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "OutputNodeEditor\&.OutputNodeEditor (\fBOutputNode\fP foNode, int nodeLayer)"

.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP OutputNodeEditor\&.getNode ()"

.PP
Implements \fBNodeEditorInterface\fP\&.
.SS "void OutputNodeEditor\&.setAction (string actionKey)"

.SS "void OutputNodeEditor\&.setActivationFunction (\fBActivationBehaviorTypes\fP activType)"

.SH "Member Data Documentation"
.PP 
.SS "\fBOutputNode\fP OutputNodeEditor\&.foNode"

.SS "int OutputNodeEditor\&.nodeLayer"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
