.TH "ResourceStore.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceStore.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResourceStore\fP"
.br
.RI "Basic unit of a resource to be stored in a \fBLand\fP object\&. \fBCreature\fP can attempt to consume this resource from the land\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
