.TH "SimRunnerUser" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimRunnerUser \- Class for running simulation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBstartSim\fP (int interval)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtilePrefab\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for running simulation\&. 


.SH "Member Function Documentation"
.PP 
.SS "void SimRunnerUser\&.startSim (int interval)"

.SH "Member Data Documentation"
.PP 
.SS "GameObject SimRunnerUser\&.tilePrefab"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
