.TH "SpeciesPopulator.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpeciesPopulator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpeciesPopulator\fP"
.br
.RI "Class for using a founder species to generate a population on the map\&. Wraps \fBPopulation\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
