.TH "ActionEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActionEditor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActionEditor\fP (\fBCreatureEditor\fP cc)"
.br
.ti -1c
.RI "void \fBsetCreator\fP (\fBActionCreatorType\fP type)"
.br
.ti -1c
.RI "\fBActionEditorAbstract\fP \fBgetActionCreator\fP ()"
.br
.ti -1c
.RI "\fBAction\fP \fBgetCreatedAction\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ActionEditor\&.ActionEditor (\fBCreatureEditor\fP cc)"

.SH "Member Function Documentation"
.PP 
.SS "\fBActionEditorAbstract\fP ActionEditor\&.getActionCreator ()"

.SS "\fBAction\fP ActionEditor\&.getCreatedAction ()"

.SS "void ActionEditor\&.setCreator (\fBActionCreatorType\fP type)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
