.TH "BoostRequirement" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoostRequirement \- Currently not used\&. Boost requirements allow for modifications to abilities, thus giving creatures with certain resources an advantage over other creatures\&. If all creatures are capable of this ability, and have the same boost requirements, they all have the opportunity to gain this advantage\&. However, it should be noted that the relationship between resources and abilities established here does give certain resources more inherent value than others\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoostRequirement\fP \fBgetShallowCopy\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Dictionary< string, int > \fBrequiredResources\fP"
.br
.RI "List of resources required for boost, and their thresholds\&. "
.ti -1c
.RI "int \fBboostAmount\fP"
.br
.RI "The amount of increase in ability if the boost is active\&. "
.in -1c
.SH "Detailed Description"
.PP 
Currently not used\&. Boost requirements allow for modifications to abilities, thus giving creatures with certain resources an advantage over other creatures\&. If all creatures are capable of this ability, and have the same boost requirements, they all have the opportunity to gain this advantage\&. However, it should be noted that the relationship between resources and abilities established here does give certain resources more inherent value than others\&. 


.SH "Member Function Documentation"
.PP 
.SS "\fBBoostRequirement\fP BoostRequirement\&.getShallowCopy ()"

.SH "Member Data Documentation"
.PP 
.SS "int BoostRequirement\&.boostAmount"

.PP
The amount of increase in ability if the boost is active\&. 
.SS "Dictionary<string, int> BoostRequirement\&.requiredResources"

.PP
List of resources required for boost, and their thresholds\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
