.TH "CommNetwork" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommNetwork \- A network that converts incomming comm signals into action recommendations\&. A seperate comm network is needed for every neightbor that sends a comm signal\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNetwork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommNetwork\fP \fBgetShallowCopy\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A network that converts incomming comm signals into action recommendations\&. A seperate comm network is needed for every neightbor that sends a comm signal\&. 


.SH "Member Function Documentation"
.PP 
.SS "\fBCommNetwork\fP CommNetwork\&.getShallowCopy ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
