.TH "CommNetwork.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommNetwork.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommNetwork\fP"
.br
.RI "A network that converts incomming comm signals into action recommendations\&. A seperate comm network is needed for every neightbor that sends a comm signal\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
