.TH "CommNodeEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommNodeEditor \- API for Comm Nodes  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeEditorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommNodeEditor\fP (\fBCommInputNode\fP _commNode, int _nodeLayer)"
.br
.ti -1c
.RI "\fBNode\fP \fBgetNode\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommInputNode\fP \fBcommNode\fP"
.br
.ti -1c
.RI "int \fBnodeLayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
API for Comm Nodes 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "CommNodeEditor\&.CommNodeEditor (\fBCommInputNode\fP _commNode, int _nodeLayer)"

.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP CommNodeEditor\&.getNode ()"

.PP
Implements \fBNodeEditorInterface\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCommInputNode\fP CommNodeEditor\&.commNode"

.SS "int CommNodeEditor\&.nodeLayer"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
