.TH "ConsumeFromLandEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsumeFromLandEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBActionEditorAbstract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsumeFromLandEditor\fP (\fBConsumeFromLand\fP inAction)"
.br
.ti -1c
.RI "void \fBsetNeighborIndex\fP (int index)"
.br
.ti -1c
.RI "void \fBsetResourceToConsume\fP (string res)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConsumeFromLandEditor\&.ConsumeFromLandEditor (\fBConsumeFromLand\fP inAction)"

.SH "Member Function Documentation"
.PP 
.SS "void ConsumeFromLandEditor\&.setNeighborIndex (int index)"

.SS "void ConsumeFromLandEditor\&.setResourceToConsume (string res)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
