.TH "CreatMenuBehav" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreatMenuBehav
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBloadCreatMenu\fP (\fBEcosystemEditor\fP ec)"
.br
.RI "load the creature editor menu using the ecosystem editor "
.ti -1c
.RI "void \fBsaveSettings\fP ()"
.br
.RI "save the creature creator's creature to the ecosystem "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBuIParent\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void CreatMenuBehav\&.loadCreatMenu (\fBEcosystemEditor\fP ec)"

.PP
load the creature editor menu using the ecosystem editor 
.SS "void CreatMenuBehav\&.saveSettings ()"

.PP
save the creature creator's creature to the ecosystem 
.SH "Member Data Documentation"
.PP 
.SS "GameObject CreatMenuBehav\&.uIParent"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
