.TH "IEcosystemEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IEcosystemEditor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCreatureEditor\fP \fBaddCreature\fP ()"
.br
.ti -1c
.RI "void \fBaddCurrentPopulationToEcosystem\fP ()"
.br
.ti -1c
.RI "void \fBaddCurrentPopulationToMap\fP ()"
.br
.ti -1c
.RI "void \fBaddResource\fP (string resourceName)"
.br
.ti -1c
.RI "void \fBaddToFounders\fP ()"
.br
.ti -1c
.RI "\fBSpeciesPopulator\fP \fBpopulateSpecies\fP (string founderSpecies)"
.br
.ti -1c
.RI "void \fBsaveCurrentPopulation\fP ()"
.br
.ti -1c
.RI "void \fBsaveEditedMap\fP ()"
.br
.ti -1c
.RI "void \fBsaveFoundersToSpecies\fP ()"
.br
.ti -1c
.RI "void \fBsaveMap\fP ()"
.br
.ti -1c
.RI "void \fBsaveResource\fP ()"
.br
.ti -1c
.RI "void \fBsaveResourceOptions\fP ()"
.br
.ti -1c
.RI "void \fBsetAbilityPointsPerCreature\fP (int abilityPoints)"
.br
.ti -1c
.RI "void \fBsetCommBits\fP (int numBits)"
.br
.ti -1c
.RI "void \fBsetDistinctPhenotypeNum\fP (int numPhenotypes)"
.br
.ti -1c
.RI "void \fBsetName\fP (string name)"
.br
.ti -1c
.RI "void \fBsetTimeUnitsPerTurn\fP (int timeUnits)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBCreatureEditor\fP IEcosystemEditor\&.addCreature ()"

.SS "void IEcosystemEditor\&.addCurrentPopulationToEcosystem ()"

.SS "void IEcosystemEditor\&.addCurrentPopulationToMap ()"

.SS "void IEcosystemEditor\&.addResource (string resourceName)"

.SS "void IEcosystemEditor\&.addToFounders ()"

.SS "\fBSpeciesPopulator\fP IEcosystemEditor\&.populateSpecies (string founderSpecies)"

.SS "void IEcosystemEditor\&.saveCurrentPopulation ()"

.SS "void IEcosystemEditor\&.saveEditedMap ()"

.SS "void IEcosystemEditor\&.saveFoundersToSpecies ()"

.SS "void IEcosystemEditor\&.saveMap ()"

.SS "void IEcosystemEditor\&.saveResource ()"

.SS "void IEcosystemEditor\&.saveResourceOptions ()"

.SS "void IEcosystemEditor\&.setAbilityPointsPerCreature (int abilityPoints)"

.SS "void IEcosystemEditor\&.setCommBits (int numBits)"

.SS "void IEcosystemEditor\&.setDistinctPhenotypeNum (int numPhenotypes)"

.SS "void IEcosystemEditor\&.setName (string name)"

.SS "void IEcosystemEditor\&.setTimeUnitsPerTurn (int timeUnits)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
