.TH "InnerInputNodeEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InnerInputNodeEditor \- API for InnerInputNodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeEditorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInnerInputNodeEditor\fP (\fBInnerInputNode\fP node, \fBCreature\fP parentCreature)"
.br
.ti -1c
.RI "\fBNode\fP \fBgetNode\fP ()"
.br
.ti -1c
.RI "void \fBsetLinkedNode\fP (string netName, int outLayerNodeIndex, int netLayer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
API for InnerInputNodes\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "InnerInputNodeEditor\&.InnerInputNodeEditor (\fBInnerInputNode\fP node, \fBCreature\fP parentCreature)"

.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP InnerInputNodeEditor\&.getNode ()"

.PP
Implements \fBNodeEditorInterface\fP\&.
.SS "void InnerInputNodeEditor\&.setLinkedNode (string netName, int outLayerNodeIndex, int netLayer)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
