.TH "Land.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Land.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLand\fP"
.br
.RI "Class for storing data about a location on the map\&. Also facilitates creature's interaction with the environment\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
