.TH "LogisticWithNegActivBehav" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogisticWithNegActivBehav \- Logistic activation function, but mapped to [-1,1]  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBActivationBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "float \fBactivFunct\fP (float input)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logistic activation function, but mapped to [-1,1] 


.SH "Member Function Documentation"
.PP 
.SS "float LogisticWithNegActivBehav\&.activFunct (float input)"

.PP
Implements \fBActivationBehavior\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
