.TH "LRMenuBehav" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LRMenuBehav
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBloadLandResMenu\fP (\fBEcosystemEditor\fP ee)"
.br
.RI "load the creature editor menu using the ecosystem editor "
.ti -1c
.RI "void \fBsaveSettings\fP ()"
.br
.RI "saves all information that the user entered into the menu "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLandResourceEditor\fP \fBlrEditor\fP"
.br
.ti -1c
.RI "GameObject \fBuIParent\fP"
.br
.ti -1c
.RI "GameObject \fBerrorObj\fP"
.br
.ti -1c
.RI "GameObject \fBamtStoredText\fP"
.br
.ti -1c
.RI "GameObject \fBmaxAmtText\fP"
.br
.ti -1c
.RI "GameObject \fBrenewAmtText\fP"
.br
.ti -1c
.RI "GameObject \fBamtConsText\fP"
.br
.ti -1c
.RI "GameObject \fBresNameText\fP"
.br
.ti -1c
.RI "GameObject \fBpropExtractText\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void LRMenuBehav\&.loadLandResMenu (\fBEcosystemEditor\fP ee)"

.PP
load the creature editor menu using the ecosystem editor 
.SS "void LRMenuBehav\&.saveSettings ()"

.PP
saves all information that the user entered into the menu 
.SH "Member Data Documentation"
.PP 
.SS "GameObject LRMenuBehav\&.amtConsText"

.SS "GameObject LRMenuBehav\&.amtStoredText"

.SS "GameObject LRMenuBehav\&.errorObj"

.SS "\fBLandResourceEditor\fP LRMenuBehav\&.lrEditor"

.SS "GameObject LRMenuBehav\&.maxAmtText"

.SS "GameObject LRMenuBehav\&.propExtractText"

.SS "GameObject LRMenuBehav\&.renewAmtText"

.SS "GameObject LRMenuBehav\&.resNameText"

.SS "GameObject LRMenuBehav\&.uIParent"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
