.TH "MainMenuBehav" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainMenuBehav
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateNewEcosystem\fP ()"
.br
.RI "provides the ecosystem menu with a new ecosystem to edit "
.ti -1c
.RI "void \fBsaveCurrentEcosystem\fP ()"
.br
.RI "saves last ecosystem edited by ecosystem menu to the ecosystem dictionary "
.ti -1c
.RI "void \fBstartSimulation\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBuIParent\fP"
.br
.ti -1c
.RI "GameObject \fBecoMenu\fP"
.br
.ti -1c
.RI "int \fBsimSteps\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void MainMenuBehav\&.createNewEcosystem ()"

.PP
provides the ecosystem menu with a new ecosystem to edit 
.SS "void MainMenuBehav\&.saveCurrentEcosystem ()"

.PP
saves last ecosystem edited by ecosystem menu to the ecosystem dictionary 
.SS "void MainMenuBehav\&.startSimulation ()"

.SH "Member Data Documentation"
.PP 
.SS "GameObject MainMenuBehav\&.ecoMenu"

.SS "int MainMenuBehav\&.simSteps"

.SS "GameObject MainMenuBehav\&.uIParent"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
