.TH "MoveAction.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveAction.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMoveAction\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmoveDir\fP { \fBmoveDir\&.up\fP, \fBmoveDir\&.down\fP, \fBmoveDir\&.left\fP, \fBmoveDir\&.right\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmoveDir\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIup \fP\fP
.TP
\fB\fIdown \fP\fP
.TP
\fB\fIleft \fP\fP
.TP
\fB\fIright \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
