.TH "MoveActionEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MoveActionEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBActionEditorAbstract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMoveActionEditor\fP (\fBMoveAction\fP a)"
.br
.ti -1c
.RI "void \fBsetDirection\fP (\fBmoveDir\fP direction)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MoveActionEditor\&.MoveActionEditor (\fBMoveAction\fP a)"

.SH "Member Function Documentation"
.PP 
.SS "void MoveActionEditor\&.setDirection (\fBmoveDir\fP direction)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
