.TH "NodeEditorInterface.cs" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeEditorInterface.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBNodeEditorInterface\fP"
.br
.RI "Interface that allows all specific node creator objects to be stored by NodeCreator class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
