.TH "ReproAction" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReproAction
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAction\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBperform\fP (\fBCreature\fP creature, \fBEcosystem\fP eco)"
.br
.ti -1c
.RI "void \fBsetPosition\fP (int[] parentPos, int neighborIndex, int[] childPosition)"
.br
.ti -1c
.RI "\fBReproAction\fP \fBshallowCopy\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "override void ReproAction\&.perform (\fBCreature\fP creature, \fBEcosystem\fP eco)\fC [virtual]\fP"

.PP
Implements \fBAction\fP\&.
.SS "void ReproAction\&.setPosition (int [] parentPos, int neighborIndex, int [] childPosition)"

.SS "\fBReproAction\fP ReproAction\&.shallowCopy ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
