.TH "ReproNetwork" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReproNetwork \- A specific kind of network that decided whether a creature should reproduce\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNetwork\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBreproduceWith\fP"
.br
.RI "Index of neighbor to reproduce with\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A specific kind of network that decided whether a creature should reproduce\&. 


.SH "Member Data Documentation"
.PP 
.SS "int ReproNetwork\&.reproduceWith"

.PP
Index of neighbor to reproduce with\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
