.TH "SensoryInputNodeEditor" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensoryInputNodeEditor \- API for SensoryInputNodes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeEditorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSensoryInputNodeEditor\fP (\fBSensoryInputNode\fP _siNode, int _nodeLayer)"
.br
.ti -1c
.RI "\fBNode\fP \fBgetNode\fP ()"
.br
.ti -1c
.RI "void \fBsetLandIndex\fP (int index)"
.br
.ti -1c
.RI "void \fBsetSensedResource\fP (string resource)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSensoryInputNode\fP \fBsiNode\fP"
.br
.ti -1c
.RI "int \fBnodeLayer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
API for SensoryInputNodes\&. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "SensoryInputNodeEditor\&.SensoryInputNodeEditor (\fBSensoryInputNode\fP _siNode, int _nodeLayer)"

.SH "Member Function Documentation"
.PP 
.SS "\fBNode\fP SensoryInputNodeEditor\&.getNode ()"

.PP
Implements \fBNodeEditorInterface\fP\&.
.SS "void SensoryInputNodeEditor\&.setLandIndex (int index)"

.SS "void SensoryInputNodeEditor\&.setSensedResource (string resource)"

.SH "Member Data Documentation"
.PP 
.SS "int SensoryInputNodeEditor\&.nodeLayer"

.SS "\fBSensoryInputNode\fP SensoryInputNodeEditor\&.siNode"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
