.TH "SimRunnerTest" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimRunnerTest \- Class for running simulation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBflipPaused\fP ()"
.br
.ti -1c
.RI "void \fBsetSteps\fP ()"
.br
.ti -1c
.RI "void \fBgetValFromSlider\fP (float value)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBtilePrefab\fP"
.br
.ti -1c
.RI "GameObject \fBstepsText\fP"
.br
.ti -1c
.RI "GameObject \fBmapSpriteObj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for running simulation\&. 


.SH "Member Function Documentation"
.PP 
.SS "void SimRunnerTest\&.flipPaused ()"

.SS "void SimRunnerTest\&.getValFromSlider (float value)"

.SS "void SimRunnerTest\&.setSteps ()"

.SH "Member Data Documentation"
.PP 
.SS "GameObject SimRunnerTest\&.mapSpriteObj"

.SS "GameObject SimRunnerTest\&.stepsText"

.SS "GameObject SimRunnerTest\&.tilePrefab"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
