.TH "ThreadManager" 3 "Tue Mar 12 2019" "Artificial Life Simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreadManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "delegate void \fBanony\fP (\fBEcosystem\fP eco)"
.br
.ti -1c
.RI "void \fBsetSteps\fP (int _steps)"
.br
.ti -1c
.RI "\fBEcosystem\fP \fBgetEcosystem\fP ()"
.br
.ti -1c
.RI "void \fBStartEcoSim\fP ()"
.br
.ti -1c
.RI "bool \fBupdateEcoIfReady\fP ()"
.br
.ti -1c
.RI "void \fBStartThreadedFunction\fP (ThreadStart someFunction)"
.br
.ti -1c
.RI "void \fBQueueMainThread\fP (\fBEcosystem\fP ecosys)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsteps\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "delegate void ThreadManager\&.anony (\fBEcosystem\fP eco)"

.SS "\fBEcosystem\fP ThreadManager\&.getEcosystem ()"

.SS "void ThreadManager\&.QueueMainThread (\fBEcosystem\fP ecosys)"

.SS "void ThreadManager\&.setSteps (int _steps)"

.SS "void ThreadManager\&.StartEcoSim ()"

.SS "void ThreadManager\&.StartThreadedFunction (ThreadStart someFunction)"

.SS "bool ThreadManager\&.updateEcoIfReady ()"

.SH "Member Data Documentation"
.PP 
.SS "int ThreadManager\&.steps"


.SH "Author"
.PP 
Generated automatically by Doxygen for Artificial Life Simulator from the source code\&.
